-- Companies Table
CREATE TABLE IF NOT EXISTS companies (
    company_id TEXT PRIMARY KEY,
    company_name TEXT,
    country TEXT,
    company_contact TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Projects Table
CREATE TABLE IF NOT EXISTS projects (
    project_id TEXT PRIMARY KEY,
    project_code TEXT UNIQUE,
    project_name TEXT,
    company_id TEXT REFERENCES companies(company_id),
    create_date DATE,
    end_date DATE,
    project_owner TEXT,
    drive_folder_link TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Owners Table
CREATE TABLE IF NOT EXISTS owners (
    owner_id TEXT PRIMARY KEY,
    owner_name TEXT,
    first_name TEXT,
    last_name TEXT,
    company TEXT,
    mobile TEXT,
    bank_account TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Currency Rates Table
CREATE TABLE IF NOT EXISTS currency_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code TEXT,
    rate_date DATE,
    rate_to_hkd NUMERIC,
    UNIQUE(currency_code, rate_date)
);

-- Currency List Table
CREATE TABLE IF NOT EXISTS currency_list (
    currency_code TEXT PRIMARY KEY
);

-- Invoices Table (Main)
CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id TEXT UNIQUE,
    invoice_date DATE,
    vendor TEXT,
    amount NUMERIC,
    currency TEXT,
    invoice_number TEXT,
    location_city TEXT,
    country TEXT,
    category TEXT,
    file_link TEXT,
    status TEXT DEFAULT 'Waiting for Confirm',
    charge_to_company TEXT,
    charge_to_project TEXT,
    owner_name TEXT,
    generated_invoice_id TEXT, -- Invoice_ID in sheet
    amount_hkd NUMERIC,
    archived_file_id TEXT,
    archived_file_link TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Statements Table
CREATE TABLE IF NOT EXISTS statements (
    id TEXT PRIMARY KEY,
    invoice_date DATE,
    vendor TEXT,
    amount NUMERIC,
    currency TEXT,
    invoice_number TEXT,
    items TEXT,
    location_city TEXT,
    country TEXT,
    category TEXT,
    file_link TEXT,
    status TEXT,
    charge_to_company TEXT,
    charge_to_project TEXT,
    owner_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Lists Table (Internal usage probably)
CREATE TABLE IF NOT EXISTS dropdown_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT,
    project_name TEXT,
    currency TEXT,
    currency_ratio NUMERIC
);

-- Indices for search optimization
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoices_file_id ON invoices(file_id);
